version: "2"
services:
  model:
    extends:
      file: docker-compose.common.yml
      service: model
    image: myambition/model:prod-latest
  users:
    extends:
      file: docker-compose.common.yml
      service: users
    image: myambition/rello:prod-latest
  rello:
    extends:
      file: docker-compose.common.yml
      service: rello
    image: myambition/rello:prod-latest
    ports:
      - 5040:${RELLO_PORT}
  web:
   image: myambition/ambition-web-table:dev
   expose:
     - "8080"
   ports:
     - "8080:8080"
  mysql:
    extends:
      file: docker-compose.common.yml
      service: mysql
    volumes:
      - mysqlvolprod:/var/lib/mysql

volumes:
  mysqlvolprod:
